name: Build Wanahomeweb front
on: [push]
jobs:         
  build:
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v1 
    - name: Install Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Build
      run: |
        cd wana_home_front
        npm install
        npm run build
        mkdir release
        cp wana_home_back/front release
    - name: Uploading
      uses: actions/upload-artifact@v1
      with:
         name: front_release
         path: release